# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-20 02:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('dt', models.CharField(max_length=100)),
                ('estadio', models.CharField(max_length=100)),
                ('ciudad', models.CharField(choices=[('santiago', 'Santiago'), ('iquique', 'Iquique'), ('antofagasta', 'Antofagasta'), ('calama', 'Calama'), ('serena', 'Serena'), ('coquimbo', 'Coquimbo'), ('valparaiso', 'Valparaiso'), ('vinadelmar', 'Vina del mar'), ('quillota', 'Quillota'), ('calera', 'Calera'), ('santiago', 'Santiago'), ('rancagua', 'Rancagua'), ('curico', 'Curico'), ('talca', 'Talca'), ('chillan', 'Chillan'), ('concepcion', 'Concepcion'), ('talcahuano', 'Talcahuano'), ('losangeles', 'Los Angeles'), ('temuco', 'Temuco'), ('ptomontt', 'Puerto Montt')], max_length=10)),
            ],
        ),
    ]
